version: '3.9'

services:
  libraryapi:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: LibraryApi/Dockerfile
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres
    container_name: postgresLibrary
    environment:
      POSTGRES_DB: LibraryDB
      POSTGRES_USER: LibraryDB
      POSTGRES_PASSWORD: LibraryDBPASSWORD
    ports:
      - 6543:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - mynetwork


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
   postgresql_data:
   pgadmin:

networks:
  mynetwork:
     driver: bridge
